### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by happylinks** [thejameskyle/backbone.service#5]
Could you please explain why we shouldn't use this anymore? (as you recently added to the README)

I'm using it in my project and am not sure what's wrong with it.

**Comment by thejameskyle** [comment]
I hate promises https://github.com/cloudflare/cf-ui/blob/master/discussions/broken-promises.md

**Comment by ahumphreys87** [comment]
hi @happylinks Ive offered to maintain this project on behalf of @thejameskyle so that we can keep the project alive for those that find it useful.
