### ISSUE TITLE
Use async/await instead of Promise

### ISSUE THREAD

**Issue by denar90** [thejameskyle/backbone.service#7]
Since babel supports async/await, maybe use it instead of Promise.

**Comment by ahumphreys87** [comment]
Could you give me an example of how it would change the code and how the usage would change?

**Comment by denar90** [comment]
Quick things how it might look like (not 100% sure, has to test it in real). 

```javascript
constructor() {
    let start = _.once(() => await this.start());
    let requests = _.result(this, 'requests');
    _.each(requests, (val, key) => {
      this.reply(key, (...args) => {
        start();
        await this[val](...args);
      });
    });

    this._super(...arguments);
  },
```

Usage example:
```javascript
      const isAuthenticated = authService.request('isAuthenticated');
      if (isAuthenticated) {
        this.$el.html('Welcome!');
        return;
      }

      this.$el.html('Permission denied.')
      authService.request('authenticate');
      this.render();
```

@ahumphreys87 But what do think about idea in general?

**Comment by ahumphreys87** [comment]
I quite like the idea. It also helps alleviate some of James' concerns. @thejameskyle what do you think?

**Comment by thejameskyle** [comment]
That code does not work at all...

You can await things in nested closures, also writing a function as an async function doesn't make it's usage work synchronously.

Writing the library using async-await doesn't change anything about how it works

**Comment by denar90** [comment]
@thejameskyle thanks, I'm closing then...
